create table if not exists public.investor_feedback (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  emoji_satisfaction text not null check (emoji_satisfaction in ('satisfied', 'neutral', 'dissatisfied')),
  reason text,
  understanding_score integer not null check (understanding_score between 1 and 5),
  selected_model text
);

alter table public.investor_feedback enable row level security;

grant insert on table public.investor_feedback to anon, authenticated;

create policy "Allow anon/authenticated insert feedback"
on public.investor_feedback
for insert
to anon, authenticated
with check (true);

