name: Node.js CI

on:
  push:
    branches: ["realtime-alpha-demo"]
  pull_request:
    branches: ["realtime-alpha-demo"]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v4
      with:
        clean: true  # Ensures a clean working directory
        fetch-depth: 0  # Fetches all history
        ref: ${{ github.ref }}  # Checks out the ref that triggered the event
    - name: Fetch Latest Changes with Git Pull
      run: |
        git pull origin realtime-alpha-demo
    - name: Debug Checkout
      run: |
        echo "Current branch: $(git branch --show-current)"
        echo "Latest commit: $(git log -1 --pretty=%H)"
        echo "Event ref: ${{ github.ref }}"
        echo "Event SHA: ${{ github.sha }}"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: echo "Running on self-hosted runner"
    - run: npm ci
    - run: npm run build --if-present
    - name: Restart the App
      run: |
        # Debugging: Show current processes and port usage
        echo "Current Node processes:"
        ps aux | grep '[n]ode' || echo "No node processes found"
        echo "Current port 3000 usage (netstat):"
        sudo netstat -tulnp | grep 3000 || echo "Nothing on port 3000 (netstat)"
        echo "Current port 3000 usage (lsof):"
        timeout 5s sudo -n lsof -i :3000 || echo "lsof timed out or found nothing"

        # Attempt to stop any process using port 3000
        echo "Attempting to free port 3000..."
        if timeout 5s sudo -n lsof -i :3000 -t | grep -q .; then
          echo "Killing processes on port 3000 (lsof)..."
          timeout 5s sudo -n lsof -i :3000 -t | xargs -r sudo -n kill -9
          sleep 2
        else
          echo "No processes found with lsof, trying ss..."
          if timeout 5s sudo -n ss -tuln -p | grep :3000 | grep -q .; then
            echo "Killing processes on port 3000 (ss)..."
            timeout 5s sudo -n ss -tuln -p | grep :3000 | awk '{print $NF}' | grep -o '[0-9]\+' | xargs -r sudo -n kill -9
            sleep 2
          else
            echo "No processes detected on port 3000"
          fi
        fi

        # Verify port is free
        if timeout 5s sudo -n lsof -i :3000; then
          echo "Port 3000 still in use! Switching to fallback port 3001..."
          PORT=3001
        else
          echo "Port 3000 is free"
          PORT=3000
        fi

        # Start the app on the chosen port
        echo "Starting the app on port $PORT..."
        npm run start -- -p $PORT &
        APP_PID=$!
        sleep 5

        # Verify the app is running
        if timeout 5s sudo -n lsof -i :$PORT; then
          echo "App is running on port $PORT (PID: $APP_PID)"
        else
          echo "Failed to start app on port $PORT" && exit 1
        fi
      shell: /usr/bin/bash -e {0}
    - run: npm test