name: NodeJS with Grunt

on:
  push:
    branches: [ "realtime-alpha-demo" ]
  pull_request:
    branches: [ "realtime-alpha-demo" ]

jobs:
  build:
    runs-on: ubuntu-irl

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - run: echo "hello world i am printed lala"

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        grunt